server:
  port: 9898

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/andresliu22/final-project.git
          clone-on-start: true
          skip-ssl-validation: true
          default-label: main
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: "guest"

management:
  security:
    enabled=false: