spring:
  application:
    name: timesheet-service
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    url: jdbc:mysql://db-fp.cts5i6uzwhsx.us-west-1.rds.amazonaws.com:3306/db_fp
    username: root
    password: password

    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: none
      show-sql: true

  main:
    allow-circular-references: true
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://Administrator:timesheet123@timesheetcluster.rv3wq.mongodb.net/final_project
      database: final_project

  cache:
    type: redis
    redis:
      time-to-live: 60000

  redis:
    port: 6379
    host: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'

amazon:
  s3:
    bucket-name: tiemsheetbucket05062022
    endpoint: https://tiemsheetbucket05062022.s3.amazonaws.com/
    #ADD ACCESS-KEY
    access-key: AKIA35ECPVJWYE6I5NH6
    #ADD SECRET-KEY
    secret-key: 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

server:
  port: ${PORT:0}

eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka