spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: timesheet-service
          uri: lb://timesheet-service
          predicates:
            - Path=/timesheet/**
        - id: composite-service
          uri: lb://composite-service
          predicates:
            - Path=/composite/**

server:
#  port: ${PORT:0}
  port: 8080

eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
