spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://db-fp.cts5i6uzwhsx.us-west-1.rds.amazonaws.com:3306/db_fp
    username: root
    password: password

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  main:
    allow-circular-references: true

server:
  port: ${PORT:0}

eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka